apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: serviceexample-latest
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: serviceexample
  policy:
    regex: "^[0-9a-f]{7,40}$"   #
